/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package edu.buffalo.cse.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int AS = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int WHERE = 8;
  /** RegularExpression Id. */
  int GROUP = 9;
  /** RegularExpression Id. */
  int ORDERTYPE = 10;
  /** RegularExpression Id. */
  int BY = 11;
  /** RegularExpression Id. */
  int UNION = 12;
  /** RegularExpression Id. */
  int ORDER = 13;
  /** RegularExpression Id. */
  int ALL = 14;
  /** RegularExpression Id. */
  int SUM = 15;
  /** RegularExpression Id. */
  int AVG = 16;
  /** RegularExpression Id. */
  int COUNT = 17;
  /** RegularExpression Id. */
  int MIN = 18;
  /** RegularExpression Id. */
  int MAX = 19;
  /** RegularExpression Id. */
  int FILE = 20;
  /** RegularExpression Id. */
  int USING = 21;
  /** RegularExpression Id. */
  int CSV = 22;
  /** RegularExpression Id. */
  int TPCH = 23;
  /** RegularExpression Id. */
  int NATURAL = 24;
  /** RegularExpression Id. */
  int JOIN = 25;
  /** RegularExpression Id. */
  int ON = 26;
  /** RegularExpression Id. */
  int CREATE = 27;
  /** RegularExpression Id. */
  int TABLE = 28;
  /** RegularExpression Id. */
  int TINT = 29;
  /** RegularExpression Id. */
  int TFLOAT = 30;
  /** RegularExpression Id. */
  int TSTRING = 31;
  /** RegularExpression Id. */
  int DECIMAL = 32;
  /** RegularExpression Id. */
  int FLOAT = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int PERIOD = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int EOS = 37;
  /** RegularExpression Id. */
  int PLUS = 38;
  /** RegularExpression Id. */
  int TIMES = 39;
  /** RegularExpression Id. */
  int MINUS = 40;
  /** RegularExpression Id. */
  int DIVIDE = 41;
  /** RegularExpression Id. */
  int EQ = 42;
  /** RegularExpression Id. */
  int NEQ = 43;
  /** RegularExpression Id. */
  int LT = 44;
  /** RegularExpression Id. */
  int LIMIT = 45;
  /** RegularExpression Id. */
  int GT = 46;
  /** RegularExpression Id. */
  int LTE = 47;
  /** RegularExpression Id. */
  int GTE = 48;
  /** RegularExpression Id. */
  int AND = 49;
  /** RegularExpression Id. */
  int OR = 50;
  /** RegularExpression Id. */
  int NOT = 51;
  /** RegularExpression Id. */
  int LPAREN = 52;
  /** RegularExpression Id. */
  int RPAREN = 53;
  /** RegularExpression Id. */
  int TRUE = 54;
  /** RegularExpression Id. */
  int FALSE = 55;
  /** RegularExpression Id. */
  int ID = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"SELECT\"",
    "\"AS\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"GROUP\"",
    "\"DESC\"",
    "\"BY\"",
    "\"UNION\"",
    "\"ORDER\"",
    "\"ALL\"",
    "\"SUM\"",
    "\"AVG\"",
    "\"COUNT\"",
    "\"MIN\"",
    "\"MAX\"",
    "\"FILE\"",
    "\"USING\"",
    "\"CSV\"",
    "\"TPCH\"",
    "\"NATURAL\"",
    "\"JOIN\"",
    "\"ON\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"INT\"",
    "\"FLOAT\"",
    "\"STRING\"",
    "<DECIMAL>",
    "<FLOAT>",
    "<STRING>",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\"LIMIT\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"(\"",
    "\")\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "<ID>",
  };

}
